### PR TITLE
Fix sampling bug

### LINKED ISSUE #32: resursive_partition() returns NA when passed a single edge
`recursive_partition()` can return a list containing NA's when passed a single edge. We also need to decide how we want to handle cases where the sample returns a single edge since you can't make a move without at least two edges. 

Steps to reproduce:
```
gudir <- igraph::graph_from_edgelist(
  matrix(c(
    c(2, 6),
    c(3, 5)
  ), ncol = 2, byrow = TRUE), directed = TRUE)

set.seed(42)
r <- sample_edges(gudir)
partitions <- recursive_partition(r)
```

### PR DESCRIPTION
**Pull request by csprock**
This resolves #32 and unblocks progress on #37. 

What I did is fix how the `sample_edges` function handles the case where there are only 1 or 2 edges in the graph being sampled by simply returning the edge set. This later gets passed to `recursive_partition` where I added a case to handle a single edge by simply passing it on. 

I then added logic in the move generator functions to filter out any edge partitions with only a single edge and to return NULL if all partitions contained single edges.

### CODE REVIEW

File: tests/testthat/test_move_pieces.R [hunk 1]
```diff
@@ -35,17 +49,21 @@ testthat::test_that(
 testthat::test_that(
     "Test that recursive_partition returns correct output lengths for n=2,3,4",
```
Comment (csprock) [inline tests/testthat/test_move_pieces.R:50]: Need to change the description to clarify what this test really does.

**Review by lizgross — APPROVED** [review]
